# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-05 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hellodocker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rtcatapp',
            name='number',
            field=models.IntegerField(default=0, verbose_name='app number'),
        ),
        migrations.AlterField(
            model_name='rtcatapp',
            name='create_date',
            field=models.DateTimeField(auto_now=True, verbose_name='date create'),
        ),
    ]
